version: '3'

networks: 
  kong-network:
    driver: bridge

volumes:
  kong-database-volume:

services:
  kong-database:
    image: postgres:9.6-alpine
    container_name: kong-database
    networks:
      - kong-network
    volumes:
      - kong-database-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: ${KONG_PG_PASSWORD:-kong}
      POSTGRES_DB: kong
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 30s
      timeout: 30s
      retries: 3
  
  kong-migration:
    image: ${KONG_DOCKER_TAG:-kong:alpine}
    container_name: kong-migration
    command: kong migrations bootstrap
    networks:
      - kong-network
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-kong}
    depends_on:
      - kong-database

  kong:
    image: ${KONG_DOCKER_TAG:-kong:alpine}
    container_name: kong
    networks:
      - kong-network
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-kong}
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    depends_on:
      - kong-database
      - kong-migration
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"

  konga-prepare:
    image: pantsel/konga:latest
    container_name: konga-prepare
    command: "-c prepare -a postgres -u postgresql://kong:${KONG_PG_PASSWORD:-kong}@kong-database:5432/konga"
    networks:
      - kong-network
    restart: on-failure
    depends_on:
      - kong-database

  konga:
    image: pantsel/konga:latest
    container_name: konga
    networks:
      - kong-network
    restart: on-failure
    environment:
      DB_ADAPTER: postgres
      DB_URI: postgresql://kong:${KONG_PG_PASSWORD:-kong}@kong-database:5432/konga
      NODE_ENV: production
    depends_on:
      - kong-database
      - konga-prepare
    ports:
      - "1337:1337"

  users:
    image: golang:1-alpine
    container_name: users
    networks:
      - kong-network
    volumes:
      - ./users:/go/src/app
    working_dir: /go/src/app
    command: go run cmd/main.go